name: Node.js CI

on:
  push:
    branches: 
      - dev
      - prod
  pull_request:
    branches: 
      - dev
      - prod

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.0]
        # We are using a specific Node.js version

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install specific npm version
      run: npm install -g npm@10.2.3

    - name: Install dependencies
      run: npm ci

    - name: Build the app
      run: npm run build --if-present

    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/prod'
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install specific npm version
      run: npm install -g npm@10.2.3

    - name: Install dependencies
      run: npm ci

    - name: Build the app
      run: npm run build --if-present

    - name: Deploy to Production
      run: |
        echo "Deploying to Production..."
        # Add your deployment script/commands here
        # e.g., scp, rsync, or using a deployment tool like `vercel` or `netlify`
